// 操作类型
const HANDLER_COLLECT = 'collect' // 收集
const HANDLER_REPLACE = 'replace' // 替换
const HANDLER_REPLACE_PRE_KEY = 'replacePreKey' // 替换正在使用的key为新字典的key

// 节点类型
const NODE_TYPE_I18N = 'NODE_TYPE_I18N';
const NODE_TYPE_CONSOLE = 'NODE_TYPE_CONSOLE';
const NODE_TYPE_STRING = 'NODE_TYPE_STRING';
const NODE_TYPE_TEMPLATE = 'NODE_TYPE_TEMPLATE';
const NODE_TYPE_JSXTEXT = 'NODE_TYPE_JSXTEXT';

const CONST_TO_FUNCTION = {
  NODE_TYPE_I18N: 'i18nHandler',
  NODE_TYPE_CONSOLE: 'consoleHandler',
  NODE_TYPE_STRING: 'stringHandler',
  NODE_TYPE_TEMPLATE: 'templateHandler',
  NODE_TYPE_JSXTEXT: 'jsxHandler',
}

module.exports = {
  HANDLER_COLLECT,
  HANDLER_REPLACE,
  HANDLER_REPLACE_PRE_KEY,

  NODE_TYPE_CONSOLE,
  NODE_TYPE_I18N,
  NODE_TYPE_STRING,
  NODE_TYPE_TEMPLATE,
  NODE_TYPE_JSXTEXT,

  CONST_TO_FUNCTION
}
