// 操作类型
const HANDLER_COLLECT = 'collect' // 收集
const HANDLER_REPLACE = 'replace' // 替换
const HANDLER_REPLACE_PRE_KEY = 'replacePreKey' // 替换正在使用的key为新字典的key

// 节点类型
const NODE_TYPE_CON_I18N = 'NODE_TYPE_CON_I18N';
const NODE_TYPE_STRING = 'NODE_TYPE_STRING';
const NODE_TYPE_TEMPLATE = 'NODE_TYPE_TEMPLATE';
const NODE_TYPE_JSXTEXT = 'NODE_TYPE_JSXTEXT';

module.exports = {
  HANDLER_COLLECT,
  HANDLER_REPLACE,
  HANDLER_REPLACE_PRE_KEY,

  NODE_TYPE_CON_I18N,
  NODE_TYPE_STRING,
  NODE_TYPE_TEMPLATE,
  NODE_TYPE_JSXTEXT
}
